export const SCROLL_BOTTOM_UPDATE_SCROLL = 'SCROLL_BOTTOM_UPDATE_SCROLL'
export const SCROLL_BOTTOM_UPDATE_CONTENT = 'SCROLL_BOTTOM_UPDATE_CONTENT'
export const SIDE_REACHED_TOP = 'SIDE_REACHED_TOP'
export const SIDE_REACED_BOTTOM = 'SIDE_REACED_BOTTOM'
export const NEW_MESSAGE = 'NEW_MESSAGE'
export const MESSAGES_READ = 'MESSAGES_READ'

export const TAKE_MESSAGES_FACTOR = 1 / 20

export const SCROLLBAR_UPDATE_DISTANCE_FACTOR = 0.8
export const SCROLLBAR_DISTANCE_DELTA = 10

export const TABLET_WIDTH_BREAK_POINT = 840
export const MOBILE_WIDTH_BREAK_POINT = 480

export const MESSAGE_WRAPPER_WIDTH_FACTOR_MOBILE = 0.95
export const MESSAGE_WRAPPER_WIDTH_FACTOR_TABLET = 0.6
export const MESSAGE_WRAPPER_WIDTH_FACTOR_DESKTOP = 0.5
